bins_pt:
- 15
- 30  
- 38  
- 48  
- 60  
- 76  
- 97  
- 122  
- 154  
- 195  
- 246
- 400 
- 1000  

bins_eta:
- -2.5  
- -2.0  
- -1.5  
- -1.0  
- -0.5  
- 0.0  
- 0.5  
- 1.0  
- 1.5  
- 2.0  
- 2.5  

processes:
- "TT"
- "QCD"
- "DY"
- "GluGlu"
- "HTo2ZdTo2Mu2X"
- "VBFH"
- "ZprimeTo2Tau"
- "WtoTauto3Mu"
- "HTo2ZdTo2Mu2X"

TT:
 pt_min: 30
 pt_max: 1000 
 eta_min: -2.5
 eta_max: 2.5

DY:
 pt_min: 30
 pt_max: 1000
 eta_min: -2.5
 eta_max: 2.5

treename:
  "DeepJetNTupler/DeepJetvars"

global_features:
- "jet_pt"
- "jet_eta"
- "jet_phi"
- "jet_energy"
- "jet_pt_corr"
- "jet_mass"
- "jet_mass_corr"
- "jet_chf"
- "jet_nhf"
- "jet_phf"
- "jet_elf"
- "jet_muf"
- "jet_ncand"
- "jet_genmatch_lep_vis_pt"
- "jet_genmatch_lep_pt"
- "jet_genmatch_wnu_pt"
- "jet_genmatch_pt"
cpf_candidates:
- "jet_pfcand_deta"
- "jet_pfcand_dphi"
- "jet_pfcand_pt_log"
- "jet_pfcand_energy_log"
- "jet_pfcand_charge"
- "jet_pfcand_frompv"
- "jet_pfcand_nlostinnerhits"
- "jet_pfcand_track_chi2"
- "jet_pfcand_track_qual"
- "jet_pfcand_dz"
- "jet_pfcand_dzsig"
- "jet_pfcand_dxy"
- "jet_pfcand_dxysig"
- "jet_pfcand_etarel"
- "jet_pfcand_pperp_ratio"
- "jet_pfcand_ppara_ratio"
- "jet_pfcand_trackjet_d3d"
- "jet_pfcand_trackjet_d3dsig"
- "jet_pfcand_trackjet_dist"
- "jet_pfcand_trackjet_decayL"
- "jet_pfcand_npixhits"
- "jet_pfcand_nstriphits"
- "jet_pfcand_pt"
- "jet_pfcand_eta"
- "jet_pfcand_phi"
- "jet_pfcand_energy"
vtx_features:
- "jet_sv_deta"
- "jet_sv_dphi"
- "jet_sv_pt_log"
- "jet_sv_mass"
- "jet_sv_ntrack"
- "jet_sv_chi2"
- "jet_sv_dxy"
- "jet_sv_dxysig"
- "jet_sv_d3d"
- "jet_sv_d3dsig"
- "jet_sv_pt"
- "jet_sv_eta"
- "jet_sv_phi"
- "jet_sv_energy"


n_cpf_candidates: 50
n_npf_candidates: 0
n_vtx_candidates: 5


truths:
  label_b: 
    # every item is connected with an AND!
    - jet_muflav:
      - 0
    - jet_elflav:
      - 0
    - jet_tauflav:
      - 0
    - jet_genmatch_hflav:
      - 5
    - jet_hflav:
      - 5
    - jet_genmatch_pt:
      - {">": 0}
    - isB:
      - 1
  label_gbb: 
    # every item is connected with an AND!
    - jet_muflav:
      - 0
    - jet_elflav:
      - 0
    - jet_tauflav:
      - 0
    - jet_genmatch_hflav:
      - 5
    - jet_hflav:
      - 5
    - jet_genmatch_pt:
      - {">": 0}
    - isGBB:
      - 1
  label_bb: 
    # every item is connected with an AND!
    - jet_muflav:
      - 0
    - jet_elflav:
      - 0
    - jet_tauflav:
      - 0
    - jet_genmatch_hflav:
      - 5
    - jet_hflav:
      - 5
    - jet_genmatch_pt:
      - {">": 0}
    - isBB:
      - 1
  label_leptonicb: 
    # every item is connected with an AND!
    - jet_muflav:
      - 0
    - jet_elflav:
      - 0
    - jet_tauflav:
      - 0
    - jet_genmatch_hflav:
      - 5
    - jet_hflav:
      - 5
    - jet_genmatch_pt:
      - {">": 0}
    - isLeptonicB:
      - 1
  label_leptonicbc: 
    # every item is connected with an AND!
    - jet_muflav:
      - 0
    - jet_elflav:
      - 0
    - jet_tauflav:
      - 0
    - jet_genmatch_hflav:
      - 5
    - jet_hflav:
      - 5
    - jet_genmatch_pt:
      - {">": 0}
    - isLeptonicB_C:
      - 1
  label_c:
    - jet_muflav:
      - 0
    - jet_elflav:
      - 0
    - jet_tauflav:
      - 0
    - jet_genmatch_hflav:
      - 4
    - jet_hflav:
      - 4
    - jet_genmatch_pt:
      - {">": 0}
    - isC:
      - 1
  label_gcc:
    - jet_muflav:
      - 0
    - jet_elflav:
      - 0
    - jet_tauflav:
      - 0
    - jet_genmatch_hflav:
      - 4
    - jet_hflav:
      - 4
    - jet_genmatch_pt:
      - {">": 0}
    - isGCC:
      - 1
  label_cc:
    - jet_muflav:
      - 0
    - jet_elflav:
      - 0
    - jet_tauflav:
      - 0
    - jet_genmatch_hflav:
      - 4
    - jet_hflav:
      - 4
    - jet_genmatch_pt:
      - {">": 0}
    - isCC:
      - 1
  label_ud:
    - jet_muflav:
      - 0
    - jet_elflav:
      - 0
    - jet_tauflav:
      - 0
    - jet_genmatch_hflav:
      - 0
    - jet_hflav: 
      - 0
    - jet_genmatch_pflav: 
       # every item is connected with an OR!
       - -3
       - -2
       - -1
       - 0
       - 1
       - 2
       - 3
    - jet_pflav: 
       # every item is connected with an OR!
       - -3
       - -2
       - -1
       - 0
       - 1
       - 2
       - 3
    - jet_genmatch_pt:
      - {">": 0}
    - isUD:
      - 1
  label_s:
    - jet_muflav:
      - 0
    - jet_elflav:
      - 0
    - jet_tauflav:
      - 0
    - jet_genmatch_hflav:
      - 0
    - jet_hflav: 
      - 0
    - jet_genmatch_pflav: 
       # every item is connected with an OR!
       - -3
       - -2
       - -1
       - 0
       - 1
       - 2
       - 3
    - jet_pflav: 
       # every item is connected with an OR!
       - -3
       - -2
       - -1
       - 0
       - 1
       - 2
       - 3
    - jet_genmatch_pt:
      - {">": 0}
    - isS:
      - 1
  label_g:
    - jet_muflav:
      - 0
    - jet_elflav:
      - 0
    - jet_tauflav:
      - 0
    - jet_genmatch_hflav:
      - 0
    - jet_hflav:
      - 0
    - jet_genmatch_pflav:
      - -21
      - 21
    - jet_pflav:
      - -21 
      - 21
    - jet_genmatch_pt:
      - {">": 0}
    - isG:
      - 1
  label_taup:
    - jet_muflav:
      - 0
    - jet_elflav:
      - 0
    - jet_tauflav:
      - 1
    - jet_taucharge:
      - {">": 0}
    - jet_genmatch_lep_vis_pt:
      - {">": 0}
  label_taum:
    - jet_muflav:
      - 0
    - jet_elflav:
      - 0
    - jet_tauflav:
      - 1
    - jet_taucharge:
      - {"<": 0}
    - jet_genmatch_lep_vis_pt:
      - {">": 0}

reference_flavour:
  "label_b"