universe = vanilla
executable = run_roc.sh
output = logs/roc_ParT_$(ClusterId).out
error = logs/roc_ParT_$(ClusterId).err
log = logs/roc_ParT_$(ClusterId).log
#output = logs/roc_ParticleNet_$(ClusterId).out
#error = logs/roc_ParticleNet_$(ClusterId).err
#log = logs/roc_ParticleNet_$(ClusterId).log

# Requesting optimal resources
request_cpus = 8
#request_memory = 48 GB
#request_gpus = 4
#request_cpus = 4
#request_memory = 16 GB
#request_gpus = 2
#request_gpus = 1

# GPU requirement (optional but recommended)
#+JobFlavour = "testmatch"
+JobFlavour = "tomorrow"
# or "tomorrow", "testmatch", etc.
#+GPUJob = True

# Make sure proxy and environment are passed
getenv = True
use_x509userproxy = True
transfer_input_files = run_roc.sh

queue